### ISSUE TITLE
Write tutorial using AI model from bioimage.io

### ISSUE THREAD

**Issue by beatrizserrano** [beatrizserrano/BH2024-project17#18]
Now that the [tool to retrieve models from bioimage.io](https://github.com/bgruening/galaxytools/pull/1391) is merged and installed, we can create a tutorial showcasing its use.

---
**Things to be done:**

 - [ ] Create the workflow.
 - [ ] Write tutorial for Galaxy Training Network:
   - [ ] How to reproduce the workflow?
   - [ ] How to use the workflow?

**Comment by kostrykin** [comment]
Is this a duplicate of https://github.com/beatrizserrano/BH2024-project17/issues/3?

**Comment by beatrizserrano** [comment]
> Is this a duplicate of #3?

it is! thanks for spotting it :)
