### ISSUE TITLE
Create a page on the Galaxy Community Hub

### ISSUE THREAD

**Issue by beatrizserrano** [beatrizserrano/BH2024-project17#22]
We don't have a page on the Galaxy Community Hub yet:

https://galaxyproject.org/community/sig

We can take inspiration from the microGalaxy community: https://galaxyproject.org/community/sig/microbial#microgalaxy-community

**Comment by beatrizserrano** [comment]
One nice-to-have feature would be to display our specific events by filtering the general events page. Is that possible @bgruening?

**Comment by bgruening** [comment]
We have the annotations with tags, but I don't think we expose this via the API yet. Maybe this is useful for the time being? https://training.galaxyproject.org/training-material/feeds/index.html

**Comment by beatrizserrano** [comment]
> We have the annotations with tags, but I don't think we expose this via the API yet. Maybe this is useful for the time being? https://training.galaxyproject.org/training-material/feeds/index.html

Hmm not sure I understand. What I meant is whether events can be filtered by `SIG` the same way it is filtered for subsites in `Regions`.
That would mean that we include a SIG name (`imaging`) in the `subsites` field, like here: https://github.com/galaxyproject/galaxy-hub/blob/46e54dbdd399fc8f2e8ef1a45cd2bcccf0508d99/content/events/2019-09-19-microscopy-imaging-analysis/index.md?plain=1#L18

**Comment by bgruening** [comment]
Can we use tags for that?

**Comment by nomadscientist** [comment]
GTN made this: https://training.galaxyproject.org/training-material/topics/single-cell/feed.w.html

**Comment by annefou** [comment]
We are working in a CoP page [https://github.com/annefou/galaxy-hub/tree/image-analysis/content/community/sig/imaging](https://github.com/annefou/galaxy-hub/tree/image-analysis/content/community/sig/imaging) but to develop together we will set up a shared document (I will post it in the main biohackathon document).

**Comment by beatrizserrano** [comment]
Currently working on https://github.com/galaxyproject/galaxy-hub/pull/2802
